import { NextResponse } from "next/server";
import connectMongoDB from "../../../../../config/mongodb";
import Room from "../../../models/Room";

export async function GET() {
  try {
    await connectMongoDB();

    const rooms = [
      { building: "Zell B. Miller Learning Center", roomNumber: "201", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "202", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "203", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "208", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "209", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "212", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "270", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "271", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "272", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "273", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "279", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "280", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "281", maxOccupancy: 6 },
      { building: "Zell B. Miller Learning Center", roomNumber: "301", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "302", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "306", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "307", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "308", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "309", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "310", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "311", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "312", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "313", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "316", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "317", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "318", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "320", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "321", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "322", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "323", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "324", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "325", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "341", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "343", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "345", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "351", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "353", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "355", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "375", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "376", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "377", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "401", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "402", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "403", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "404", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "405", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "406", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "407", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "408", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "409", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "410", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "411", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "412", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "413", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "414", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "415", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "416", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "418", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "441", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "442", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "443", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "444", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "445", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "446", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "451", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "452", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "453", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "454", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "455", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "456", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "466", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "467", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "468", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "469", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "470", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "471", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "472", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "473", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "474", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "475", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "476", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "477", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "478", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "479", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "480", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "481", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "482", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "483", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "484", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "485", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "486", maxOccupancy: 8 },
      { building: "Zell B. Miller Learning Center", roomNumber: "487", maxOccupancy: 8 },

      { building: "Shirley Mathis McBay Science Library", roomNumber: "441A", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441B", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441C", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441D", maxOccupancy: 5 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441E", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441F", maxOccupancy: 5 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441G", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441H", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441J", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441K", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441L", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "441M", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442A", maxOccupancy: 5 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442B", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442C", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442D", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442E", maxOccupancy: 5 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442F", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442G", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442H", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442J", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442K", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442L", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442M", maxOccupancy: 3 },
      { building: "Shirley Mathis McBay Science Library", roomNumber: "442N", maxOccupancy: 3 },

      { building: "Main Library", roomNumber: "132", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "133", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "134", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "141", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "142", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "143", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "144", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "145", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "146", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "147", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "161", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "162", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "163", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "171", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "172", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "173", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "174", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "175", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "176", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "177", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "178", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "181", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "182", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "183", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "184", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "185", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "186", maxOccupancy: 4 },
      { building: "Main Library", roomNumber: "187", maxOccupancy: 4 },

      { building: "Russell Hall", roomNumber: "Floor 1 TV Lounge", maxOccupancy: 10 },
      { building: "Russell Hall", roomNumber: "Floor 2 TV Lounge", maxOccupancy: 10 },
      { building: "Russell Hall", roomNumber: "Floor 3 TV Lounge", maxOccupancy: 10 },
      { building: "Russell Hall", roomNumber: "Floor 4 TV Lounge", maxOccupancy: 10 },
      { building: "Russell Hall", roomNumber: "Floor 5 TV Lounge", maxOccupancy: 10 },
      { building: "Russell Hall", roomNumber: "Floor 6 TV Lounge", maxOccupancy: 10 },
      { building: "Russell Hall", roomNumber: "Floor 7 TV Lounge", maxOccupancy: 10 },
      { building: "Russell Hall", roomNumber: "Floor 8 TV Lounge", maxOccupancy: 10 },
      { building: "Russell Hall", roomNumber: "Floor 9 TV Lounge", maxOccupancy: 10 },
      { building: "Russell Hall", roomNumber: "Floor 10 TV Lounge", maxOccupancy: 10 },

      { building: "Brumby Hall", roomNumber: "Floor 1 TV Lounge", maxOccupancy: 10 },
      { building: "Brumby Hall", roomNumber: "Floor 2 TV Lounge", maxOccupancy: 10 },
      { building: "Brumby Hall", roomNumber: "Floor 3 TV Lounge", maxOccupancy: 10 },
      { building: "Brumby Hall", roomNumber: "Floor 4 TV Lounge", maxOccupancy: 10 },
      { building: "Brumby Hall", roomNumber: "Floor 5 TV Lounge", maxOccupancy: 10 },
      { building: "Brumby Hall", roomNumber: "Floor 6 TV Lounge", maxOccupancy: 10 },
      { building: "Brumby Hall", roomNumber: "Floor 7 TV Lounge", maxOccupancy: 10 },
      { building: "Brumby Hall", roomNumber: "Floor 8 TV Lounge", maxOccupancy: 10 },
      { building: "Brumby Hall", roomNumber: "Floor 9 TV Lounge", maxOccupancy: 10 },

      { building: "Creswell Hall", roomNumber: "Floor 1 TV Lounge", maxOccupancy: 10 },
      { building: "Creswell Hall", roomNumber: "Floor 2 TV Lounge", maxOccupancy: 10 },
      { building: "Creswell Hall", roomNumber: "Floor 3 TV Lounge", maxOccupancy: 10 },
      { building: "Creswell Hall", roomNumber: "Floor 4 TV Lounge", maxOccupancy: 10 },
      { building: "Creswell Hall", roomNumber: "Floor 5 TV Lounge", maxOccupancy: 10 },
      { building: "Creswell Hall", roomNumber: "Floor 6 TV Lounge", maxOccupancy: 10 },
      { building: "Creswell Hall", roomNumber: "Floor 7 TV Lounge", maxOccupancy: 10 },
      { building: "Creswell Hall", roomNumber: "Floor 8 TV Lounge", maxOccupancy: 10 },
      { building: "Creswell Hall", roomNumber: "Floor 9 TV Lounge", maxOccupancy: 10 },

      { building: "Black-Diallo-Miller Hall", roomNumber: "Floor 1 TV Lounge", maxOccupancy: 10 },
      { building: "Black-Diallo-Miller Hall", roomNumber: "Floor 2 TV Lounge", maxOccupancy: 10 },
      { building: "Black-Diallo-Miller Hall", roomNumber: "Floor 3 TV Lounge", maxOccupancy: 10 },
      { building: "Black-Diallo-Miller Hall", roomNumber: "Floor 4 TV Lounge", maxOccupancy: 10 },
      { building: "Black-Diallo-Miller Hall", roomNumber: "Floor 5 TV Lounge", maxOccupancy: 10 },
      { building: "Black-Diallo-Miller Hall", roomNumber: "Floor 6 TV Lounge", maxOccupancy: 10 },

      { building: "Building 1516", roomNumber: "Floor 1 TV Lounge", maxOccupancy: 10 },
      { building: "Building 1516", roomNumber: "Floor 2 TV Lounge", maxOccupancy: 10 },
      { building: "Building 1516", roomNumber: "Floor 3 TV Lounge", maxOccupancy: 10 },
      { building: "Building 1516", roomNumber: "Floor 4 TV Lounge", maxOccupancy: 10 },
      { building: "Building 1516", roomNumber: "Floor 5 TV Lounge", maxOccupancy: 10 },
      { building: "Building 1516", roomNumber: "Floor 6 TV Lounge", maxOccupancy: 10 },
    ];

    await Room.deleteMany({ building: { $ne: "Tate Student Center" } });
    await Room.insertMany(rooms);

    return NextResponse.json({ success: true, message: `Seeded ${rooms.length} rooms` });
  } catch (error: any) {
    console.error("Seed Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}